runtime: go
api_version: go1
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
handlers:
  - url: /css
    static_dir: css
    mime_type: text/css
  - url: /js
    static_dir: js
    mime_type: application/javascript

# - url: /bootstrap/fonts/(.*\.(woff|woff2|ttf))$
#   upload: bootstrap/fonts/.*\.(woff|woff2|ttf)$
#   static_files: bootstrap/fonts/\1
#   mime_type: font/.*\.(woff|woff2|ttf)$

# - url: /bootstrap/fonts/(.*\.svg)$
#   upload: bootstrap/fonts/(.*\.svg)$
#   static_files: bootstrap/fonts/\1
#   mime_type: image/svg+xml

# - url: /bootstrap/fonts/(.*\.eot)$
#   upload: bootstrap/fonts/(.*\.eot)$
#   static_files: bootstrap/fonts/\1
#   mime_type: application/vnd.ms-fontobject

  - url: /.*
    script: _go_app
