name: Deploy-GAE
on:
  push:
    branches:
      - master
jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
      with:
        submodules: true
        fetch-depth: 0
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.5.0
      with:
        hugo-version: 'latest'
    - name: Build
      run: hugo --minify
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy
      run: gcloud app deploy --quiet app.yaml
  slack:
    name: Slack
    needs: BuildAndDeploy # set needs only last job except this job
    runs-on: ubuntu-latest
    if: always() # set always
    steps:
        # run this action to get workflow conclusion
        # You can get conclusion via env (env.WORKFLOW_CONCLUSION)
      - uses: technote-space/workflow-conclusion-action@v3.0.0
      - uses: 8398a7/action-slack@v3
        if: env.WORKFLOW_CONCLUSION == 'failure' # notify only if failure
        with:
          # status: ${{ env.WORKFLOW_CONCLUSION }} # neutral, success, skipped, cancelled, timed_out, action_required, failure
          status: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}